const $=s=>document.querySelector(s), app=$('#app');
const qs=new URLSearchParams(location.search), mode=qs.get('mode')==='controller'?'controller':'stage';
const COLORS=['#cf6c63','#d0a950','#7089b9','#729d78','#a879b2','#67a7a8'];
const NAMES=['Mara','Ivo','Nix','Odo','Vale','Pip'];
const POSES={
 stand:[.12,.05,-.12,-.05,.04,.02,-.04,-.02,0],
 point:[1.48,1.48,-.18,-.08,.02,0,-.03,0,-.05],
 cheer:[2.55,2.75,-2.55,-2.75,.08,-.04,-.08,.04,0],
 shrug:[1.02,1.9,-1.02,-1.9,.03,0,-.03,0,0],
 crouch:[.25,.5,-.25,-.5,.38,-.55,-.38,.55,.13]
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clean=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);
function roomCode(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:5},()=>c[Math.floor(Math.random()*c.length)]).join('')}
const peerId=r=>`puppetalk-${r.toLowerCase()}`;
const send=(c,m)=>{if(c?.open)c.send(m)};
const room=clean(qs.get('room'));
if(mode==='controller') controller(room); else stage(room||roomCode());

function stage(room){
 if(!window.Matter||!window.Peer){app.textContent='Puppetalk libraries failed to load.';return}
 const u=new URL(location.href);u.search='';u.searchParams.set('room',room);history.replaceState(null,'',u);
 const join=new URL(location.href);join.search='';join.searchParams.set('mode','controller');join.searchParams.set('room',room);
 app.innerHTML=`<section class="stage-shell"><div class="stage-topbar"><div class="brand"><strong>Puppetalk</strong><div class="small muted" id="status">opening stage…</div></div><div class="join-card"><div class="small muted">JOIN ROOM</div><div class="room-code">${room}</div><div class="small muted join-link">${join.href}</div></div></div><canvas id="stage-canvas"></canvas></section>`;
 const canvas=$('#stage-canvas'),ctx=canvas.getContext('2d'),status=$('#status');
 const {Engine,Bodies,Body,Composite,Constraint,Vector}=Matter, engine=Engine.create({enableSleeping:false});engine.gravity.y=1.05;engine.gravity.scale=.001;
 let W=1,H=1,last=performance.now(),bounds=[];const puppets=new Map(),conns=new Map();
 function resize(){W=Math.max(innerWidth,320);H=Math.max(innerHeight,360);const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);bounds.forEach(b=>Composite.remove(engine.world,b));bounds=[Bodies.rectangle(W/2,H+10,W+160,80,{isStatic:true,friction:.9}),Bodies.rectangle(-30,H/2,60,H*2,{isStatic:true}),Bodies.rectangle(W+30,H/2,60,H*2,{isStatic:true})];Composite.add(engine.world,bounds)}
 const joint=(a,pa,b,pb)=>Constraint.create({bodyA:a,pointA:pa,bodyB:b,pointB:pb,length:1,stiffness:.97,damping:.13});
 function make(slot){
  if(puppets.has(slot))return puppets.get(slot);const x=W*(.16+slot*.135),y=Math.min(H-170,H*.62),group=Body.nextGroup(true),opt={collisionFilter:{group},frictionAir:.04,restitution:.08,friction:.8};
  const torso=Bodies.rectangle(x,y,48,78,{...opt,chamfer:{radius:13},density:.0022}),head=Bodies.circle(x,y-65,26,{...opt,density:.0018}),uaL=Bodies.rectangle(x-37,y-17,16,52,opt),faL=Bodies.rectangle(x-42,y+30,15,49,opt),uaR=Bodies.rectangle(x+37,y-17,16,52,opt),faR=Bodies.rectangle(x+42,y+30,15,49,opt),thL=Bodies.rectangle(x-14,y+65,19,58,opt),shL=Bodies.rectangle(x-14,y+118,17,54,opt),thR=Bodies.rectangle(x+14,y+65,19,58,opt),shR=Bodies.rectangle(x+14,y+118,17,54,opt);
  const cs=[joint(torso,{x:0,y:-39},head,{x:0,y:24}),joint(torso,{x:-24,y:-27},uaL,{x:0,y:-25}),joint(uaL,{x:0,y:25},faL,{x:0,y:-23}),joint(torso,{x:24,y:-27},uaR,{x:0,y:-25}),joint(uaR,{x:0,y:25},faR,{x:0,y:-23}),joint(torso,{x:-14,y:38},thL,{x:0,y:-27}),joint(thL,{x:0,y:27},shL,{x:0,y:-25}),joint(torso,{x:14,y:38},thR,{x:0,y:-27}),joint(thR,{x:0,y:27},shR,{x:0,y:-25})];
  const p={slot,color:COLORS[slot],name:NAMES[slot],torso,head,uaL,faL,uaR,faR,thL,shL,thR,shR,bodies:[torso,head,uaL,faL,uaR,faR,thL,shL,thR,shR],cs,target:{x:x/W,y:y/H},pose:'stand',rag:false,mouth:0};Composite.add(engine.world,[...p.bodies,...cs]);puppets.set(slot,p);return p
 }
 function remove(slot){const p=puppets.get(slot);if(!p)return;p.bodies.forEach(b=>Composite.remove(engine.world,b));p.cs.forEach(c=>Composite.remove(engine.world,c));puppets.delete(slot)}
 function delta(t,c){let d=t-c;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return d}
 function servo(b,t,s=.006){b.torque+=clamp(delta(t,b.angle)*s-b.angularVelocity*s*.72,-.028,.028)}
 function drive(p){const t=p.torso,dx=clamp(p.target.x*W,70,W-70)-t.position.x,dy=clamp(p.target.y*H,120,H-86)-t.position.y,k=p.rag?.000055:.000075;Body.applyForce(t,t.position,{x:dx*k-t.velocity.x*.0024,y:dy*k-t.velocity.y*.0024});if(p.rag)return;const q=POSES[p.pose]||POSES.stand,b=q[8];servo(t,b,.008);servo(p.head,b*.35,.0045);[p.uaL,p.faL,p.uaR,p.faR,p.thL,p.shL,p.thR,p.shR].forEach((x,i)=>servo(x,b+q[i],i%2?.005:.006))}
 function wp(b,p){const r=Vector.rotate(p,b.angle);return{x:b.position.x+r.x,y:b.position.y+r.y}}
 function chain(a,c,w){ctx.beginPath();ctx.moveTo(a[0].x,a[0].y);a.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.lineCap=ctx.lineJoin='round';ctx.strokeStyle='#08090a';ctx.lineWidth=w+6;ctx.stroke();ctx.strokeStyle=c;ctx.lineWidth=w;ctx.stroke()}
 function puppet(p){const t=p.torso,c=p.color;const sl=wp(t,{x:-24,y:-27}),sr=wp(t,{x:24,y:-27}),el=wp(p.uaL,{x:0,y:25}),er=wp(p.uaR,{x:0,y:25}),wl=wp(p.faL,{x:0,y:23}),wr=wp(p.faR,{x:0,y:23}),hl=wp(t,{x:-14,y:38}),hr=wp(t,{x:14,y:38}),kl=wp(p.thL,{x:0,y:27}),kr=wp(p.thR,{x:0,y:27}),al=wp(p.shL,{x:0,y:25}),ar=wp(p.shR,{x:0,y:25});chain([hl,kl,al],c,17);chain([hr,kr,ar],c,17);chain([sl,el,wl],c,15);chain([sr,er,wr],c,15);ctx.save();ctx.translate(t.position.x,t.position.y);ctx.rotate(t.angle);ctx.fillStyle='#08090a';ctx.roundRect(-27,-42,54,84,16);ctx.fill();ctx.fillStyle=c;ctx.roundRect(-24,-39,48,78,13);ctx.fill();ctx.restore();ctx.save();ctx.translate(p.head.position.x,p.head.position.y);ctx.rotate(p.head.angle);ctx.fillStyle='#08090a';ctx.beginPath();ctx.arc(0,0,29,0,7);ctx.fill();ctx.fillStyle=c;ctx.beginPath();ctx.arc(0,0,26,0,7);ctx.fill();ctx.fillStyle='#08090a';ctx.beginPath();ctx.arc(-8,-5,2.7,0,7);ctx.arc(8,-5,2.7,0,7);ctx.fill();ctx.beginPath();p.mouth===0?ctx.roundRect(-7,9,14,3,2):p.mouth===1?ctx.roundRect(-7,6,14,10,5):ctx.ellipse(0,10,9,11,0,0,7);ctx.fill();ctx.restore();ctx.font='600 12px system-ui';ctx.textAlign='center';ctx.fillStyle='#eee';ctx.fillText(p.name,p.head.position.x,p.head.position.y-40)}
 function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createRadialGradient(W/2,H*.72,10,W/2,H*.72,Math.max(W,H)*.8);g.addColorStop(0,'#292b30');g.addColorStop(.48,'#17191c');g.addColorStop(1,'#0c0d0f');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#ffffff14';for(let x=-W;x<W*2;x+=74){ctx.beginPath();ctx.moveTo(W/2+(x-W/2)*.22,H*.66);ctx.lineTo(x,H-30);ctx.stroke()}puppets.forEach(puppet)}
 function tick(n){const dt=clamp(n-last,8,25);last=n;puppets.forEach(drive);Engine.update(engine,dt);draw();requestAnimationFrame(tick)}
 function statusNow(extra=''){status.textContent=`${conns.size} puppeteer${conns.size===1?'':'s'} connected${extra?' — '+extra:''}`}
 function free(){for(let i=0;i<6;i++)if(!conns.has(i))return i;return-1}
 function input(slot,m){if(m?.type!=='input')return;const p=make(slot),i=m.input||{};if(Number.isFinite(i.x))p.target.x=clamp(i.x,.04,.96);if(Number.isFinite(i.y))p.target.y=clamp(i.y,.18,.9);if(POSES[i.pose])p.pose=i.pose;if(typeof i.rag==='boolean')p.rag=i.rag;if(Number.isInteger(i.mouth))p.mouth=clamp(i.mouth,0,2)}
 const peer=new Peer(peerId(room));peer.on('open',()=>status.textContent='stage live — waiting for puppeteers');peer.on('connection',c=>{const s=free();if(s<0){c.on('open',()=>{send(c,{type:'full'});setTimeout(()=>c.close(),120)});return}conns.set(s,c);make(s);c.on('open',()=>{send(c,{type:'welcome',slot:s,name:NAMES[s]});statusNow()});c.on('data',m=>input(s,m));const bye=()=>{if(conns.get(s)===c)conns.delete(s);remove(s);statusNow()};c.on('close',bye);c.on('error',bye)});peer.on('error',e=>{console.error(e);status.textContent=e.type==='unavailable-id'?'room code already in use — reload':'network error: '+(e.type||'unknown')});addEventListener('resize',resize,{passive:true});resize();requestAnimationFrame(tick)
}

function controller(room){
 if(!window.Peer){app.textContent='Puppetalk network library failed to load.';return}
 if(!room){app.innerHTML=`<section class="join-form"><form class="join-panel card" id="join"><strong>Puppetalk</strong><div class="muted small">Join a stage</div><label>Room code<input id="code" maxlength="8" placeholder="ABCDE" required></label><button class="primary">Join</button></form></section>`;$('#join').onsubmit=e=>{e.preventDefault();const r=clean($('#code').value);if(!r)return;const u=new URL(location.href);u.search='';u.searchParams.set('mode','controller');u.searchParams.set('room',r);location.href=u};return}
 app.innerHTML=`<section class="shell controller-shell"><header class="controller-head"><div><strong>Puppetalk</strong><div class="small muted">room ${room}</div></div><div class="small"><span class="status-dot" id="dot"></span><span id="ct">connecting</span></div></header><div class="move-pad" id="pad"><span class="pad-label">drag your puppet</span><span class="pad-nub" id="nub"></span></div><section class="card grid"><div class="small muted">POSE</div><div class="grid pose-grid" id="poses">${Object.keys(POSES).map((p,i)=>`<button data-pose="${p}" class="${i?'':'active'}">${p}</button>`).join('')}<button data-rag>Go limp</button></div></section><section class="card voice-card"><div><strong>Voice mouth</strong><div class="small muted">Analysed on this phone; audio is not transmitted.</div></div><div class="voice-meter"><span id="level"></span></div><button class="primary" id="mic">Enable microphone</button><button id="talk">Hold to talk manually</button></section><section class="card grid action-grid"><button id="centre">Centre puppet</button><button id="retry">Reconnect</button></section></section>`;
 const dot=$('#dot'),ct=$('#ct'),pad=$('#pad'),nub=$('#nub'),mic=$('#mic'),level=$('#level'),talk=$('#talk');let peer,conn,micStop;const state={x:.5,y:.55,pose:'stand',rag:false,mouth:0};let last='';
 const stat=(t,s='')=>{ct.textContent=t;dot.className='status-dot '+s};
 function tx(force=false){if(!conn?.open)return;const b=JSON.stringify(state);if(!force&&b===last)return;last=b;send(conn,{type:'input',input:state})}
 function connect(){if(peer&&!peer.destroyed)peer.destroy();stat('connecting');peer=new Peer();peer.on('open',()=>{stat('joining…');conn=peer.connect(peerId(room),{serialization:'json',reliable:false});conn.on('data',m=>{if(m?.type==='welcome'){stat('you are '+(NAMES[m.slot]||m.name),'live');last='';tx(true)}if(m?.type==='full')stat('room is full','bad')});conn.on('close',()=>stat('stage disconnected','bad'));conn.on('error',()=>stat('connection error','bad'))});peer.on('error',e=>stat(e.type==='peer-unavailable'?'stage not found':'network error: '+(e.type||'unknown'),'bad'))}
 let down=false;const move=e=>{if(!down)return;const r=pad.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1),y=clamp((e.clientY-r.top)/r.height,0,1);nub.style.left=x*100+'%';nub.style.top=y*100+'%';state.x=.05+x*.9;state.y=.22+y*.66;tx()};pad.onpointerdown=e=>{down=true;pad.setPointerCapture(e.pointerId);move(e)};pad.onpointermove=move;pad.onpointerup=pad.onpointercancel=()=>down=false;
 $('#poses').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pose){state.pose=b.dataset.pose;state.rag=false;document.querySelectorAll('[data-pose]').forEach(x=>x.classList.toggle('active',x===b));const r=$('[data-rag]');r.classList.remove('active');r.textContent='Go limp'}else if(b.hasAttribute('data-rag')){state.rag=!state.rag;b.classList.toggle('active',state.rag);b.textContent=state.rag?'Recover':'Go limp'}tx(true)};
 $('#centre').onclick=()=>{state.x=.5;state.y=.55;nub.style.left=nub.style.top='50%';tx(true)};$('#retry').onclick=connect;
 mic.onclick=async()=>{if(micStop){micStop();micStop=null;mic.textContent='Enable microphone';state.mouth=0;level.style.width='0%';tx(true);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),ac=new AudioContext(),an=ac.createAnalyser(),data=new Uint8Array(512);an.fftSize=512;an.smoothingTimeConstant=.46;ac.createMediaStreamSource(stream).connect(an);let raf,lastM=-1,lastT=0;const sample=n=>{an.getByteTimeDomainData(data);let sum=0;data.forEach(v=>{const x=(v-128)/128;sum+=x*x});const rms=Math.sqrt(sum/data.length);level.style.width=clamp(rms*540,0,100)+'%';const m=rms>.028?(rms>.105?2:1):0;if(m!==lastM&&n-lastT>45){state.mouth=m;lastM=m;lastT=n;tx(true)}raf=requestAnimationFrame(sample)};raf=requestAnimationFrame(sample);micStop=()=>{cancelAnimationFrame(raf);stream.getTracks().forEach(t=>t.stop());ac.close()};mic.textContent='Disable microphone'}catch(e){console.error(e);stat('microphone unavailable','bad')}};
 const manual=on=>{state.mouth=on?2:0;talk.classList.toggle('active',on);tx(true)};talk.onpointerdown=e=>{e.preventDefault();manual(true)};talk.onpointerup=talk.onpointercancel=()=>manual(false);talk.onpointerleave=e=>{if(e.buttons)manual(false)};connect()
}
